version: '3'
services:
  selenium-grid:
    image: selenium/standalone-chrome:beta
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-grid
    volumes:
      - ./:/app
    stop_grace_period: 5s
    stop_signal: SIGINT
    command: >
      /usr/bin/env bash -c "
      trap 'rm -rf /app/build' SIGINT;
      tail -f /dev/null"
    network_mode: host
