version: 2.1
workflows:
  version: 2
  build-and-run:
    jobs:
      - build-and-run

jobs:
  build-and-run:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout

      - run:
          name: Set up Docker and docker-compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Build with Gradle
          command: ./joke.sh

      - run:
          name: Commit files
          command: |
            git config --global user.name "circleci"
            git config --global user.email "circleci@circleci.com"
            git commit -am "Verify Selenium success with CI/CD"


